# ?? ??
server.port=8080

# ??? ??? ?? ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/climbdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=juclimb
spring.datasource.password=3429

# ??? Thymeleaf ??
spring.thymeleaf.cache=false

# ??? Output ?? (ANSI ??)
spring.output.ansi.enabled=ALWAYS

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.config-location=classpath:mybatis-config.xml
